import { ALPHABET, ID_LENGTH } from './constants';
import type { Config } from './types';

/**
 * Returns a randomly-generated friendly ID.
 * Note that the friendly ID is not guaranteed to be
 * unique to any other ID generated by this same method,
 * so it is up to you to check for uniqueness.
 * @return {String} friendly ID.
 */
export function generate({ alphabet = ALPHABET, prefix = '', idLength = ID_LENGTH }: Config): string {
  let key = '_';

  for (let i = 0; i < (idLength - 1); i++) {
    key = `${key}${alphabet.charAt(
      Math.floor(Math.random() * alphabet.length)
    )}`;
  }

  return `${prefix}${key}`;
}
